### ISSUE TITLE
Allow users to select their zone from an interactive map

### ISSUE THREAD

**Issue by mattcookxyz** [codeforkansascity/nra_calc#7]
Jud Knapp has a file of polygons representing the zones that can be loaded into QGIS mapping software (free/open-source).

Maybe we can try to overlay these on a Leaflet.js map for users to select their zone from (built on outputs of issue #8)

**Comment by bbradforddesign** [comment]
Polygons successfully added to map. Will add selection functionality.

**Comment by bbradforddesign** [comment]
Selection feedback added. Will revise in future issue to fix errors and improve functionality.
